apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tiller-deploy
  namespace: kube-system
  labels:
    app: helm
    name: tiller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helm
        name: tiller
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: docker/default
    spec:
      priorityClassName: tiller-high-priority
      tolerations:
      - key: "gravitational.io/runlevel"
        value: system
        operator: Equal
        # allows to run on master nodes
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      securityContext:
        runAsUser: -1
      containers:
        - name: tiller
          image: gcr.io/kubernetes-helm/tiller:canary
          imagePullPolicy: IfNotPresent
          command: ["/tiller"]
          args: ["--listen=127.0.0.1:44134"]
          securityContext:
            runAsUser: -1
          env:
            - name: TILLER_NAMESPACE
              value: kube-system
            - name: TILLER_HISTORY_MAX
              value: "100"
          livenessProbe:
            httpGet:
              path: /liveness
              port: 44135
            initialDelaySeconds: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /readiness
              port: 44135
            initialDelaySeconds: 1
            timeoutSeconds: 1
---
apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: tiller-high-priority
value: 1000000
globalDefault: false
description: "This priority class for tiller pods."
